name-template: 'v$NEXT_PATCH_VERSION'
tag-template: 'v$NEXT_PATCH_VERSION'

template: |
  ## Heavens Above Release $NEXT_PATCH_VERSION

  ###  Features
  $CHANGES

  ### Contributors
  $CONTRIBUTORS

categories:
  - title: ' Features'
    labels:
      - feature
      - enhancement
  - title: 'Fixes'
    labels:
      - bug
      - fix
  - title: ' Maintenance'
    labels:
      - chore
      - cleanup

change-template: '- $TITLE @$AUTHOR (#$NUMBER)'
version-template: '$MAJOR.$MINOR.$PATCH'
no-changes-template: 'No significant changes this release.'
