site_name: Heavens Above Project Docs
site_description: Documentation for the Heavens Above automation and deployment project.
site_author: Amna I233073
repo_url: https://github.com/i233073/heavens-above
repo_name: i233073/heavens-above
edit_uri: edit/main/docs/

theme:
  name: material
  features:
    - navigation.instant       # Faster page transitions
    - navigation.tabs           # Tabs for top-level sections
    - navigation.sections       # Sidebar sections
    - toc.integrate             # Table of contents inside the sidebar
    - content.code.copy         # Copy button on code blocks
    - content.action.edit       # “Edit this page” button
    - content.tabs.link         # Link between tabbed code blocks
  palette:
    - media: "(prefers-color-scheme: light)"
      scheme: default
      primary: blue
      accent: indigo
    - media: "(prefers-color-scheme: dark)"
      scheme: slate
      primary: indigo
      accent: blue
  icon:
    repo: fontawesome/brands/github

nav:
  - Home: index.md
  - Usage: usage.md
  - CI Workflow: ci-workflow.md
  - Code Review: code-review.md
  - Deployment: deployment.md
  - About:
      - Overview: about.md
      - Credits: credits.md

plugins:
  - search
  - git-revision-date-localized:
      fallback_to_build_date: true
  - tags
  - mkdocs-simple-hooks:
      hooks:
        on_pre_build: |
          print("Building Heavens Above documentation...")

markdown_extensions:
  - admonition
  - codehilite
  - footnotes
  - toc:
      permalink: true
  - def_list
  - attr_list
  - tables
  - tasklist
  - pymdownx.details
  - pymdownx.superfences
  - pymdownx.inlinehilite
  - pymdownx.tabbed:
      alternate_style: true
